### ISSUE TITLE
No primary keys table sync issue!

### ISSUE THREAD

**Issue by hexin1217263985** [mrjgreen/db-sync#20] opened 2017-04-01 07:49 UTC
Thanks for the code. It's a nice tool to sync data fo MySQL, but for the table that there is no primary key, can't sync data.May it possible to manully define  multi-columns as a 'primary key' to locate checksum caculation to sync no primary key's table.

**Comment by mrjgreen** [comment] 2017-04-06 22:43
This seems to be a duplicate of #7
Sorry to copy paste, but here is the response from the last time this was asked:

Firstly... Every table I can think of (that would need to be "DbSync-ed") should probably have a key :) (I'm interested to hear of new use cases though!)

The tool uses "insert on duplicate key update" to insert or update the row on the remote server. In theory if the table had a unique key that wasn't the primary it would work. But I'm not sure I see the reasoning.

Let me know if I can be of any further help, and thanks for your feedback!

**Closed as completed by mrjgreen** 2017-04-06 22:43 UTC

**Comment by sayajin101** [comment] 2018-10-15 11:59
good day,

I having this issue as well where its throwing an error complaining about `The table radius.radusergroup does not have a primary key`.

by default the freeRadius table radusergroup does not have a primary or unique key, the only thing
it does have is an index on the username.

Unfortunately I am unable to edit the structure of the table since it is a clients, how do I get around this?

**Comment by mrjgreen** [comment] 2018-10-21 10:42
Unfortunately dbsync can only work on tables with a primary key. 

Cheers
Joe Green
